# Generated by Django 4.1.4 on 2023-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('success', 'Delivred'), ('danger', 'Canceled'), ('warning', 'Wait for confirmation'), ('primary', 'Out for delivery')], default='warning', max_length=50),
        ),
    ]
