# Generated by Django 4.1.4 on 2023-01-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('green', 'Delivred'), ('red', 'Canceled'), ('yellow', 'Wait for confirmation')], default='yellow', max_length=50),
        ),
    ]
