# Generated by Django 4.1.4 on 2023-01-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('D', 'Delivred'), ('C', 'Canceled'), ('W', 'Wait for confirmation'), ('O', 'Out for delivery')], default='W', max_length=50),
        ),
    ]
